"""baseline schema

Full schema as of v0.3 (first Alembic revision adopted onto a project previously using
``Base.metadata.create_all()``; see docs/DATABASE_DEPLOYMENT.md). Generated by autogenerate
against an empty database, then hand-fixed: added the missing ``bdo.models`` import autogenerate
omits for the custom ``UTCDateTime`` type, and de-duplicated the CheckConstraint entries
autogenerate emits twice per enum column (same name — PostgreSQL rejects two constraints sharing
a name in one ``CREATE TABLE``).

Revision ID: 0001_baseline_schema
Revises:
Create Date: 2026-10-01 14:29:42.420385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import bdo.models


# revision identifiers, used by Alembic.
revision: str = '0001_baseline_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('agency', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('data_domain', sa.String(length=512), nullable=True),
    sa.Column('access_mode', sa.String(length=32), nullable=False),
    sa.Column('typical_freshness_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MANUAL', 'UNAVAILABLE', 'DEGRADED', 'UNKNOWN', name='source_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('default_evidence_class', sa.Enum('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED', name='source_evidence_class', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_healthcheck_at', bdo.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_health_message', sa.Text(), nullable=True),
    sa.Column('created_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("default_evidence_class IN ('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED')", name='source_evidence_class'),
    sa.CheckConstraint("status IN ('ACTIVE', 'MANUAL', 'UNAVAILABLE', 'DEGRADED', 'UNKNOWN')", name='source_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', bdo.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED', name='ingest_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('records_retrieved', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('stations_upserted', sa.Integer(), nullable=False),
    sa.Column('snapshots_saved', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED')", name='ingest_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_measurement_at', bdo.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('payload_path', sa.String(length=1024), nullable=True),
    sa.Column('payload_text', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('ingest_run_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_path')
    )
    op.create_index(op.f('ix_raw_snapshots_payload_hash'), 'raw_snapshots', ['payload_hash'], unique=False)
    op.create_table('source_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('collector_run_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latest_measurement_at', bdo.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('freshness_label', sa.String(length=16), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['collector_run_id'], ['ingest_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_history_source_checked', 'source_health_history', ['source_id', 'checked_at'], unique=False)
    op.create_table('field_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_observation_id', sa.String(length=128), nullable=True),
    sa.Column('observed_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('evidence_class', sa.Enum('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED', name='fieldobs_evidence_class', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('phenomenon', sa.String(length=128), nullable=False),
    sa.Column('water_depth_cm', sa.Float(), nullable=True),
    sa.Column('passability', sa.Enum('normal', 'pedestrian_only', 'motorcycle_only', 'high_clearance_only', 'impassable', 'unknown', name='passability', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('trend', sa.Enum('rising', 'stable', 'falling', 'dry', 'unknown', name='trend', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('photo_ref', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_class IN ('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED')", name='fieldobs_evidence_class'),
    sa.CheckConstraint("passability IN ('normal', 'pedestrian_only', 'motorcycle_only', 'high_clearance_only', 'impassable', 'unknown')", name='passability'),
    sa.CheckConstraint("trend IN ('rising', 'stable', 'falling', 'dry', 'unknown')", name='trend'),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_observation_id', name='uq_field_obs_ext')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_station_id', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('catchment', sa.String(length=128), nullable=True),
    sa.Column('operator', sa.String(length=256), nullable=True),
    sa.Column('state_variable', sa.String(length=128), nullable=True),
    sa.Column('actuator_or_capacity', sa.String(length=256), nullable=True),
    sa.Column('upstream_nodes_text', sa.Text(), nullable=True),
    sa.Column('downstream_nodes_text', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('UNVERIFIED', 'TYPE_INFERRED', 'VERIFIED_DOCUMENT', 'VERIFIED_FIELD', 'DEPRECATED', name='validation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=True),
    sa.Column('coordinate_evidence_class', sa.Enum('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED', name='coord_evidence_class', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('raw_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("coordinate_evidence_class IN ('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED')", name='coord_evidence_class'),
    sa.CheckConstraint("validation_status IN ('UNVERIFIED', 'TYPE_INFERRED', 'VERIFIED_DOCUMENT', 'VERIFIED_FIELD', 'DEPRECATED')", name='validation_status'),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_station_id', name='uq_station_source_ext')
    )
    op.create_table('derived_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('period_start', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('period_end', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('method_version', sa.String(length=64), nullable=False),
    sa.Column('evidence_class', sa.Enum('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED', name='metric_evidence_class', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('input_provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_class IN ('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED')", name='metric_evidence_class'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('external_record_id', sa.String(length=256), nullable=True),
    sa.Column('variable', sa.String(length=128), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('measurement_at', bdo.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('evidence_class', sa.Enum('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED', name='measurement_evidence_class', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('quality_flag', sa.String(length=512), nullable=True),
    sa.Column('raw_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('ingest_run_id', sa.Integer(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', bdo.models.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_class IN ('OBSERVED', 'OFFICIAL_REPORTED', 'THIRD_PARTY_REPORTED', 'MODELLED', 'ASSUMED')", name='measurement_evidence_class'),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_runs.id'], ),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_measurement_dedup')
    )
    op.create_index('ix_measurement_station_var_time', 'measurements', ['station_id', 'variable', 'measurement_at'], unique=False)
    op.create_index('ix_measurement_time', 'measurements', ['measurement_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_measurement_time', table_name='measurements')
    op.drop_index('ix_measurement_station_var_time', table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('derived_metrics')
    op.drop_table('stations')
    op.drop_table('field_observations')
    op.drop_index('ix_health_history_source_checked', table_name='source_health_history')
    op.drop_table('source_health_history')
    op.drop_index(op.f('ix_raw_snapshots_payload_hash'), table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_table('ingest_runs')
    op.drop_table('sources')
    # ### end Alembic commands ###
